web:
  build: .
  command: rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - RAILS_ENV=dev_docker
  env_file:
    - .env
db:
  image: postgres:10.4-alpine
  ports:
    - 5432:5432